"""Made Cart Model

Revision ID: 4b2ea09e1dcd
Revises: fddbb79ae13a
Create Date: 2024-12-11 22:30:20.877433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2ea09e1dcd'
down_revision = 'fddbb79ae13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
