"""Remade status field

Revision ID: 5ef1a3b085d7
Revises: 8d39360371aa
Create Date: 2024-12-13 18:46:04.874235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef1a3b085d7'
down_revision = '8d39360371aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
