"""Add in_stock in Product model

Revision ID: 81fed96d6d23
Revises: cbd816eac836
Create Date: 2024-12-11 22:40:48.825569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fed96d6d23'
down_revision = 'cbd816eac836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
