"""Made Order Model

Revision ID: cbd816eac836
Revises: 4b2ea09e1dcd
Create Date: 2024-12-11 22:34:32.565108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd816eac836'
down_revision = '4b2ea09e1dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
